on:
  workflow_dispatch

jobs:
  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          source-url: https://nuget.pkg.github.com/cronique/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        
          
      - name: Build solution and generate NuGet package
        run: 
          dotnet build --configuration Release

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "**/*.nupkg" --skip-duplicate --no-symbols true
